Repository lightvue/lightvue, pull requests merged in 2022-10, with the labels that each got.

#159 Fixed typo error
  docs/src/pages/getting-started/installation.vue
Labels: hacktoberfest-accepted, Hacktoberfest

#161 fixed the convention
  docs/src/components/landing-page/SectionEnterprise.vue
  docs/src/pages/vue-components/button.vue
  examples/button/ButtonAPI.js
Labels: Hacktoberfest

#165 Fixed typo in checkbox
  docs/src/pages/vue-components/checkbox.vue
Labels: Hacktoberfest

#167 Corrected spelling in color picker
  docs/src/pages/vue-components/color-picker.vue
Labels: Hacktoberfest

#146 Added the full process of contribution.
  CONTRIBUTING.md
Labels: hacktoberfest-accepted
